### ISSUE TITLE
test api

### ISSUE THREAD

**Issue by kjappelbaum** [gSulpizio/pyGAPSAPI#1]
if you talk about this line https://github.com/gSulpizio/pyGAPSAPI/blob/5185cff744e15dcf57ff2f91b9c7fc275db9ddcd/api/tests/testAPI.py#L6 you're in the wrong folder

**Comment by kjappelbaum** [comment]
it would work if this test file is on the top level of the repo, where you could import from a package called `test` or if you are in a folder that has the file `app`

**Comment by gSulpizio** [comment]
I did a workaround for now, couldn't get it to work the way I wanted for now
